#!/bin/bash 

#PBS -l nodes=1:ppn=1
#PBS -l walltime=130:30:00 
#PBS -q tmnt

cd $PBS_O_WORKDIR
/bin/hostname

module load gcc/4.8.5 openmpi/3.1.4
source $HOME/OpenFOAM/OpenFOAM-6/etc/bashrc

# Source tutorial clean functions
#. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#cleanCase

blockMesh | tee log.block
renumberMesh -overwrite | tee log.renumber

pimpleFoam | tee log.Foam



